# Generated by Django 4.2 on 2023-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('email1', models.CharField(max_length=200, null=True)),
                ('date_cretaed', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
