# Generated by Django 4.2 on 2023-05-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_tag_tag_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name1',
            new_name='name',
        ),
    ]
