# Generated by Django 4.2 on 2023-05-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
